@startuml
'https://plantuml.com/class-diagram

class Baralla{
-cartes:List<Carta>
--Mètodes--
+barrejar()
+seguentCarta()
+cartesDisponibles
+demanarCartes(num:Int):List<Carta>
+repartirCartes(num:Int):List<Carta>
+veureMunt()
}
class Carta{
-pal:String
-numero:Int
}
class jugador{
-baralla:List<Carta>
--Mètodes--
+ rebreCartes(cartes: List<Carta>)
+ retornarCartes(): List<Carta>
+ veureCartes(): List<Carta>
}
@enduml