@startuml
left to right direction

actor "Jugador" as Jugador

rectangle "Joc de Cartes" {
    usecase "Barrejar Cartes" as barrejar
    usecase "Obtenir Següent Carta" as seguentCarta
    usecase "Comprovar Cartes Disponibles" as cartesDisponibles
    usecase "Demanar Cartes" as demanarCartes
    usecase "Repartir Cartes" as repartirCartes
    usecase "Veure Cartes al Munt" as veureMunt
}

Jugador --> barrejar
Jugador --> seguentCarta
Jugador --> cartesDisponibles
Jugador --> demanarCartes
Jugador --> repartirCartes
Jugador --> veureMunt
@enduml